### ISSUE TITLE
Проект не собирается из-за отсутствия google-services.json и крашится при инициализации Firebase

### ISSUE THREAD

**Issue by iandreyshev** [mrDevGo/Telegram#1]
Об этом не сказано в описании проекта, поэтому считаю, что требуется предупреждение, либо доработка.
Проект сложно склонировать, запустить и попробовать

Если закомментировать применение плагина, который требует google-services.json, то проект будет падать при вызове функции `initFirebase()`

**Comment by petrovyuri** [comment]
Здравствуйте, для запуска проекта, необходимо клонировать репозиторий, создать новый проект  в Firebase, получить файл google-services.json. Скопировать его в папку app. В данном видео подробно это показано: https://www.youtube.com/watch?v=bx5MLV4Wyn8

В redmi добавлю, спасибо.
![Снимок](https://user-images.githubusercontent.com/48598325/88919054-26aa7a00-d273-11ea-9a10-f5641e9aa313.PNG)
